import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/toaster";
import "@uploadthing/react/styles.css";
import "./globals.css";
import Header from "@/components/client/Header";
import { auth } from "@/auth";
import { getUserData } from "@/actions/user";
import { FrontEndUser } from "@/types/type";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userSession = await auth();
  let user = null;
  if (userSession) {
    user = (await getUserData(
      String(userSession?.user?.email)
    )) as FrontEndUser;
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header user={user} />
        <div className="mt-[60px]">{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
